# -*- coding: utf-8 -*-
"""Henrique.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r2IkJUDeY5fDwKGD4ttpIrng-otm4ClZ
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

# Commented out IPython magic to ensure Python compatibility.
# clone YOLOv7 repository
# %cd {HOME}
!git clone https://github.com/WongKinYiu/yolov7

# navigate to yolov7 directory and checkout u7 branch of YOLOv7 - this is hash of lates commit from u7 branch as of 12/21/2022
# %cd {HOME}/yolov7
!git checkout 44f30af0daccb1a3baecc5d80eae22948516c579

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov7/seg
!pip install --upgrade pip
!pip install -r requirements.txt

from getpass import getpass

# copy your API KEY from 
api_key = getpass('Enter YOUR_API_KEY secret value: ')

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov7/seg

!pip install roboflow --quiet

from roboflow import Roboflow

rf = Roboflow(api_key=api_key)
project = rf.workspace("university-bswxt").project("crack-bphdr")
dataset = project.version(2).download("yolov7")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov7/seg
!python segment/train.py --batch 16 \
 --epochs 10 \
 --data {dataset.location}/data.yaml \
 --weights $WEIGHTS_PATH \
 --device 0 \
 --name custom

from IPython.display import Image, display

display(Image(filename=f"{HOME}/yolov7/seg/runs/train-seg/custom/val_batch0_labels.jpg"))

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov7/seg
!python segment/predict.py \
--weights {HOME}/yolov7/seg/runs/train-seg/custom/weights/best.pt \
--conf 0.25 \
--source {dataset.location}/test/images

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov7/seg/runs/predict-seg/exp/*.jpg')[:2]:
      display(Image(filename=imageName))
      print("\n")